version: '3'
services:
  myapp:
    build: .  
    ports:
     - "8080:8080"
    network_mode: "host"
    hostname: localhost
  redis:
    image: "redis:alpine"
    network_mode: "host"
    hostname: localhost
